### ISSUE TITLE
JOSE: Paper contents

### ISSUE THREAD

**Issue by lechten** [GWC-DCMB/curriculum-notebooks#10]
This is related to your [JOSE submission](https://github.com/openjournals/jose-reviews/issues/138).

The paper is well written and addresses the questions relevant to JOSE. I've got some comments/questions:

At the end of the summary you write that anyone can contribute. I suggest to emphasize that you describe Open Educational Resources (OER) under free and open licenses. Actually, I wonder about the videos. They do not indicate license information, do they? Are they OER too? Are they only available on Youtube or also elsewhere for download and reuse?

Section "Collaborative Curriculum Development"
- You describe a process of quality control via PRs. I do not see those PRs in this repository. Are they publicly visible somewhere?
- JOSE papers prominently feature a link to the repository. Thus, the link at the end of the section may not be necessary. Besides, is this section really the best place for such a link?

I suggest to phrase learning objectives with action verbs (what will students be able to *do*?). The first objective is too vague in this regard, while the other two are fine.

You write about "paired programming". I suggest "pair programming".

**Comment by kelly-sovacool** [comment]
Thank you for your comments, Jens!

1. We added the OER phrase to the summary in PR #21.
1. CC-BY also applies to the videos. The descriptions on YouTube list the license (you have to click 'show more' to see it). We updated the language in our license file here to explicitly mention the videos in PR #21. Currently, they are only available on YouTube. Would you suggest making them available for download on another platform also?
1. We've gone through a couple rounds of reorganizing/restructuring since we began this project. In addition to in this repo, PRs can be viewed [here](https://github.com/GWC-DCMB/SummerExperience/pulls?q=is%3Apr+is%3Aclosed) and [here](https://github.com/GWC-DCMB/ClubCurriculum/pulls?page=1&q=is%3Apr+is%3Aclosed).
1. We removed the link to GitHub at the end of the Section "Collaborative Curriculum Development" since it's redundant and doesn't flow naturally.
1. We rephrased the learning objectives in PR #18.
1. We switched "paired programming" to "pair programming" in PR #18.

**Comment by lechten** [comment]
Thank you for the improvements and explanations!

Yes, I would indeed suggest to make the videos available elsewhere, but that is just my personal opinion and unrelated to the review process: I see Google as driver of [surveillance capitalism](https://en.wikipedia.org/wiki/Surveillance_capitalism) and I would not want to force students into that surveillance to use my OER.

**Comment by kelly-sovacool** [comment]
@lechten one of the options we were thinking of was to put the videos on Google Drive and make them viewable publicly because we have free space through our University. Although still via Google, I think that would still be an improvement over only having them on YouTube? We're interested if you have other ideas.

**Comment by lechten** [comment]
The [5 Rs of openness](https://opencontent.org/blog/archives/3221) require a download (retain) option, which is missing on YouTube. Yes, with Google Drive this requirement would be met.

I do not have own experiences in sharing videos, so the following are just vague suggestions. Maybe [OER Commons](https://www.oercommons.org/about) would be a good place. Also [Wikimedia Commons](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Screencast) and [Internet Archive](https://help.archive.org/hc/en-us/articles/360002360111-Uploading-A-Basic-Guide) host videos.
