### ISSUE TITLE
PDF output not perfect

### ISSUE THREAD

**Issue by lechten** [GWC-DCMB/curriculum-notebooks#13]
Lists are not properly converted to PDF, e.g., the list of data types at the end of this file: https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/_Keys/pdf/KEY_Lesson03_Variables_Types.pdf

Images do not appear to be embedded, e.g., the if-elif-else diagram is not contained in that file: https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/_Keys/pdf/KEY_Lesson09_Conditionals.pdf

**Comment by lechten** [comment]
The function analogy table in https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/_Keys/pdf/KEY_Lesson19_Functions.pdf is broken.

**Comment by lechten** [comment]
[Lesson 24](https://github.com/GWC-DCMB/curriculum-notebooks/blob/main/Lessons/_Keys/pdf/KEY_Lesson24_Basic_Stats_IV_Significance.pdf) ends on page 1.

**Comment by kelly-sovacool** [comment]
Unfortunately, these problems are limitations of `jupyter nbconvert` and are not in our control.

We originally created the workflow to create PDFs of our Jupyter Notebooks because GitHub had just started to support rendering/displaying of Jupyter Notebooks online, and it was sometimes prohibitively slow. GitHub now does a much better job of displaying them quickly in the web browser, so the PDFs are less necessary.
